/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tahir.motogplusservice.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.tahir.motogplusservice.model.Khaliq;
import com.tahir.motogplusservice.service.KhaliqLocalServiceUtil;

/**
 * The extended model base implementation for the Khaliq service. Represents a row in the &quot;moto_Khaliq&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link KhaliqImpl}.
 * </p>
 *
 * @author TahirNoor
 * @see KhaliqImpl
 * @see Khaliq
 * @generated
 */
@ProviderType
public abstract class KhaliqBaseImpl extends KhaliqModelImpl implements Khaliq {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a khaliq model instance should use the {@link Khaliq} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			KhaliqLocalServiceUtil.addKhaliq(this);
		}
		else {
			KhaliqLocalServiceUtil.updateKhaliq(this);
		}
	}
}