/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tahir.meeting.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Himalaya service. Represents a row in the &quot;meeting_Himalaya&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.tahir.meeting.model.impl.HimalayaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.tahir.meeting.model.impl.HimalayaImpl}.
 * </p>
 *
 * @author Tahir Noor
 * @see Himalaya
 * @see com.tahir.meeting.model.impl.HimalayaImpl
 * @see com.tahir.meeting.model.impl.HimalayaModelImpl
 * @generated
 */
@ProviderType
public interface HimalayaModel extends BaseModel<Himalaya>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a himalaya model instance should use the {@link Himalaya} interface instead.
	 */

	/**
	 * Returns the primary key of this himalaya.
	 *
	 * @return the primary key of this himalaya
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this himalaya.
	 *
	 * @param primaryKey the primary key of this himalaya
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this himalaya.
	 *
	 * @return the uuid of this himalaya
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this himalaya.
	 *
	 * @param uuid the uuid of this himalaya
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the himalaya ID of this himalaya.
	 *
	 * @return the himalaya ID of this himalaya
	 */
	public long getHimalayaId();

	/**
	 * Sets the himalaya ID of this himalaya.
	 *
	 * @param himalayaId the himalaya ID of this himalaya
	 */
	public void setHimalayaId(long himalayaId);

	/**
	 * Returns the group ID of this himalaya.
	 *
	 * @return the group ID of this himalaya
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this himalaya.
	 *
	 * @param groupId the group ID of this himalaya
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this himalaya.
	 *
	 * @return the company ID of this himalaya
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this himalaya.
	 *
	 * @param companyId the company ID of this himalaya
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this himalaya.
	 *
	 * @return the user ID of this himalaya
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this himalaya.
	 *
	 * @param userId the user ID of this himalaya
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this himalaya.
	 *
	 * @return the user uuid of this himalaya
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this himalaya.
	 *
	 * @param userUuid the user uuid of this himalaya
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this himalaya.
	 *
	 * @return the user name of this himalaya
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this himalaya.
	 *
	 * @param userName the user name of this himalaya
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this himalaya.
	 *
	 * @return the create date of this himalaya
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this himalaya.
	 *
	 * @param createDate the create date of this himalaya
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this himalaya.
	 *
	 * @return the modified date of this himalaya
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this himalaya.
	 *
	 * @param modifiedDate the modified date of this himalaya
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this himalaya.
	 *
	 * @return the name of this himalaya
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this himalaya.
	 *
	 * @param name the name of this himalaya
	 */
	public void setName(String name);

	/**
	 * Returns the designation of this himalaya.
	 *
	 * @return the designation of this himalaya
	 */
	@AutoEscape
	public String getDesignation();

	/**
	 * Sets the designation of this himalaya.
	 *
	 * @param designation the designation of this himalaya
	 */
	public void setDesignation(String designation);

	/**
	 * Returns the comapany of this himalaya.
	 *
	 * @return the comapany of this himalaya
	 */
	@AutoEscape
	public String getComapany();

	/**
	 * Sets the comapany of this himalaya.
	 *
	 * @param comapany the comapany of this himalaya
	 */
	public void setComapany(String comapany);

	/**
	 * Returns the dob of this himalaya.
	 *
	 * @return the dob of this himalaya
	 */
	public Date getDob();

	/**
	 * Sets the dob of this himalaya.
	 *
	 * @param dob the dob of this himalaya
	 */
	public void setDob(Date dob);

	/**
	 * Returns the doj of this himalaya.
	 *
	 * @return the doj of this himalaya
	 */
	public Date getDoj();

	/**
	 * Sets the doj of this himalaya.
	 *
	 * @param doj the doj of this himalaya
	 */
	public void setDoj(Date doj);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.tahir.meeting.model.Himalaya himalaya);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.tahir.meeting.model.Himalaya> toCacheModel();

	@Override
	public com.tahir.meeting.model.Himalaya toEscapedModel();

	@Override
	public com.tahir.meeting.model.Himalaya toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}